---
- name: Deploy NGINX container
  hosts: your_server
  become: yes

  tasks:
    - name: Pull NGINX image
      docker_image:
        name: nginx
        tag: latest

    - name: Start NGINX container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"